// Copyright (c) 2019 Robert Rypuła - https://github.com/robertrypula

export const BYTE_UNIQUE_VALUES = 256;
export const MILLISECONDS_IN_SECOND = 1000;
export const NYQUIST_TWICE = 2;
export const SILENCE_FREQUENCY = 0;

export const FREQUENCY_MARGIN = 600;
export const FREQUENCY_08_KHZ = 8000;
export const FREQUENCY_16_KHZ = 16000;
export const FREQUENCY_20_KHZ = 20000;
export const FREQUENCY_FORBIDDEN_RANGE = [
  [FREQUENCY_08_KHZ - FREQUENCY_MARGIN, FREQUENCY_08_KHZ + FREQUENCY_MARGIN],
  [FREQUENCY_16_KHZ - FREQUENCY_MARGIN, FREQUENCY_16_KHZ + FREQUENCY_MARGIN],
  [FREQUENCY_20_KHZ - FREQUENCY_MARGIN, +Infinity]
];
export const FREQUENCY_END_LOWER = FREQUENCY_08_KHZ - FREQUENCY_MARGIN;
export const FREQUENCY_END_UPPER = FREQUENCY_16_KHZ - FREQUENCY_MARGIN;
export const FREQUENCY_END_INAUDIBLE = FREQUENCY_20_KHZ - FREQUENCY_MARGIN;
